# Import NumPy

NumPy is a Python library used for working with arrays and numerical calculations.

In this cell, we import NumPy and give it the short name `np`, which is the standard way of using NumPy.


In [18]:
# Cell 1

# Import the NumPy library
import numpy as np

# Check NumPy Version

Every library has different versions.

This cell prints the installed version of NumPy so we know which version we are using.

In [19]:
# Cell 2

# Print the installed NumPy version
print(np.__version__)

2.3.5


# Creating a 1D Array

A 1D array is similar to a Python list but is much faster for mathematical operations.

In this cell, we:
- Create a NumPy array.
- Multiply every element by 2.
- Print the updated array.
- Print the data type of the object.

In [20]:
# Cell 3

# Create a 1D NumPy array
array = np.array([1,2,3,4])

# Multiply every element by 2
array = array * 2

# Print the updated array
print (array)

# Print the type of the object
print (type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


# Creating a 3D Array

A 3D array contains multiple 2D arrays.

In this example:
- We create a 3 × 3 × 3 array containing letters.
- Print the number of dimensions.
- Print the shape of the array.
- Access one specific element using indexing.
- Combine three letters to form a word.

In [21]:
# Cell 4

# Create a 3D NumPy array

array = np.array([[["A","B","C"], ["D","E","F"], ["G","H","I"]],
                                        [["J","K","L"], ["M","N","O"], ["P","Q","R"]],
                                        [["S","T","U"], ["V","W","X"], ["Y","Z","_"]]])

# Print the number of dimensions
print(array.ndim)

# Print the shape (layers, rows, columns)
print(array.shape)

# Access a specific element
print(array[1,1,1])

# Combine letters from different positions to create a word
word = array[0,0,0] + array[2,0,0] + array[1,0,1]

# Print the final word
print(word)

3
(3, 3, 3)
N
ASK


# NumPy Slicing in a 2D Array

In this cell, we create a **4 × 4 NumPy array** and perform different types of slicing and indexing operations.

The following operations are demonstrated:

1. **Access a Single Element** – Retrieve one specific value using row and column indexes.
2. **Access a Complete Row** – Retrieve all elements from a selected row.
3. **Access a Complete Column** – Retrieve all elements from a selected column.
4. **Slice Rows** – Select multiple rows from the array.
5. **Slice Columns** – Select multiple columns from the array.
6. **Submatrix** – Select a smaller section of the array by slicing both rows and columns.
7. **Every Second Row** – Retrieve every alternate row using the step value.
8. **Every Second Column** – Retrieve every alternate column using the step value.
9. **Reverse Rows** – Display the rows in reverse order.
10. **Reverse Columns** – Display the columns in reverse order.
11. **Reverse Entire Matrix** – Reverse both rows and columns to flip the entire matrix.
12. **Main Diagonal** – Extract the diagonal elements from the array.

This example helps understand the basic slicing and indexing techniques used with 2D NumPy arrays.

In [22]:
# Cell 5

# Create a 4 × 4 NumPy array
array = np.array([[1,2,3,4],
                                        [5,6,7,8],
                                        [9,10,11,12],
                                        [13,14,15,16]])

print("Original Array")
print(array)

# 1. Access a Single Element
print("\n1. Single Element:")
print(array[2,1])

# 2. Access a Complete Row
print("\n2. Complete Row")
print(array[1])

# 3. Access a Complete Column
print("\n3. Complete Column:")
print(array[:,2])

# 4. Slice Rows
print("\n4. Slice Rows:")
print(array[1:3])

# 5. Slice Columns
print("\n5. Slice Columns:")
print(array[:, 1:3])

# 6. Slice Rows and Columns (Submatrix)
print("\n6. Submatrix:")
print(array[1:3, 1:3])

# 7. Every Second Row
print("\n7. Every Second row:")
print(array[::2])

# 8. Every Second Column
print("\n8. Every Second Column")
print(array[:, ::2])

# 9. Reverse Rows
print("\n9. Reverse Rows:")
print(array[::-1])

# 10. Reverse Columns
print("\n10. Reverse Columns:")
print(array[:, ::-1])

# 11. Reverse Entire Matrix
print("\n11. Reverse Entire Matrix:")
print(array[::-1, ::-1])

# 12. Main Diagonal
print("\n12. Main Diagonal:")
print(array.diagonal())

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

1. Single Element:
10

2. Complete Row
[5 6 7 8]

3. Complete Column:
[ 3  7 11 15]

4. Slice Rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]

5. Slice Columns:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

6. Submatrix:
[[ 6  7]
 [10 11]]

7. Every Second row:
[[ 1  2  3  4]
 [ 9 10 11 12]]

8. Every Second Column
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

9. Reverse Rows:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

10. Reverse Columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

11. Reverse Entire Matrix:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

12. Main Diagonal:
[ 1  6 11 16]


# NumPy Arithmetic and Mathematical Operations

In this cell, we create a **1D NumPy array** containing decimal values and perform different arithmetic and mathematical operations.

The following operations are demonstrated:

1. **Addition** – Adds a value to each element of the array.
2. **Subtraction** – Subtracts a value from each element.
3. **Multiplication** – Multiplies each element by a value.
4. **Division** – Divides each element by a value.
5. **Power** – Raises each element to a specified power.
6. **Modulus** – Returns the remainder after division.
7. **Square Root** – Calculates the square root of each element.
8. **Absolute Value** – Returns the positive value of each element.
9. **Round** – Rounds each element to the nearest integer.
10. **Floor** – Rounds each element down to the nearest integer.
11. **Ceiling** – Rounds each element up to the nearest integer.
12. **Exponential** – Calculates the value of \(e^x\) for each element.
13. **Natural Logarithm** – Computes the natural logarithm (base \(e\)) of each element.
14. **Log Base 10** – Computes the logarithm with base 10.
15. **Sine** – Calculates the sine of each element.
16. **Cosine** – Calculates the cosine of each element.
17. **Tangent** – Calculates the tangent of each element.
18. **Maximum Value** – Finds the largest value in the array.
19. **Minimum Value** – Finds the smallest value in the array.
20. **Clip Values** – Limits all values within a specified range.
21. **Pi Constant** – Displays the mathematical constant π (pi).

This example demonstrates the most commonly used arithmetic and mathematical functions available in NumPy.

In [23]:
# Cell 6

# Create a NumPy array
array = np.array([1.99,2.99,3.99])

print("Original Array:")
print(array)

# 1. Addition
print("\n1. Addition (+1):")
print(array  + 1)

# 2. Subtraction
print("\n2. Subtraction (-2):")
print(array - 2)

# 3. Multiplication
print("\n3. Multiplication (*3):")
print(array * 3)

# 4. Division
print("\n4. Division (/4):")
print(array / 4)

# 5. Power
print("\n5. Power(**5):")
print(array ** 5)

# 6. Modulus
print("\n6. Modulus (%2):")
print(array % 2)

# 7. Square Root
print("\n7. Square Root:")
print(np.sqrt(array))

# 8. Absolute Value
print("\n8. Absolute Value:")
print(np.abs(array))

# 9. Round
print("\n9. Round:")
print(np.round(array))

# 10. Floor
print("\n10. Floor:")
print(np.floor(array))

# 11. Ceiling
print("\n11. Ceiling:")
print(np.ceil(array))

# 12. Exponential (e^x)
print("\n12. Exponential:")
print(np.exp(array))

# 13. Natural Logarithm
print("\n13. Natural Logarithm:")
print(np.log(array))

# 14. Log Base 10
print("\n14. Log Base 10:")
print(np.log10(array))

# 15. Sine
print("\n15. Sine:")
print(np.sin(array))

# 16. Cosine
print("\n16. Cosine:")
print(np.cos(array))

# 17. Tangent
print("\n17. Tangent:")
print(np.tan(array))

# 18. Maximum Value
print("\n18. Maximum Values:")
print(np.max(array))

# 19. Minimum Value
print("\n19. Minimum Value:")
print(np.min(array))

# 20. Clip Values (2 to 3)
print("\n20. Clip Values (2 to 3):")
print(np.clip(array,2,3))

# 21. Pi Constant
print("\n21. Pi Constant:")
print(np.pi)

Original Array:
[1.99 2.99 3.99]

1. Addition (+1):
[2.99 3.99 4.99]

2. Subtraction (-2):
[-0.01  0.99  1.99]

3. Multiplication (*3):
[ 5.97  8.97 11.97]

4. Division (/4):
[0.4975 0.7475 0.9975]

5. Power(**5):
[  31.2079601   238.97691015 1011.2638402 ]

6. Modulus (%2):
[1.99 0.99 1.99]

7. Square Root:
[1.4106736  1.72916165 1.99749844]

8. Absolute Value:
[1.99 2.99 3.99]

9. Round:
[2. 3. 4.]

10. Floor:
[1. 2. 3.]

11. Ceiling:
[2. 3. 4.]

12. Exponential:
[ 7.31553376 19.88568249 54.05488936]

13. Natural Logarithm:
[0.68813464 1.09527339 1.38379123]

14. Log Base 10:
[0.29885308 0.47567119 0.6009729 ]

15. Sine:
[ 0.91341336  0.15101271 -0.75022833]

16. Cosine:
[-0.40703321 -0.98853182 -0.66117884]

17. Tangent:
[-2.24407578 -0.15276464  1.13468291]

18. Maximum Values:
3.99

19. Minimum Value:
1.99

20. Clip Values (2 to 3):
[2.   2.99 3.  ]

21. Pi Constant:
3.141592653589793


# NumPy Broadcasting

In this cell, we demonstrate the concept of **broadcasting** in NumPy.

Broadcasting is a feature that allows NumPy to perform arithmetic operations on arrays of different shapes without manually resizing them. NumPy automatically expands the smaller array to match the shape of the larger array whenever the dimensions are compatible.

The following broadcasting examples are demonstrated:

1. **Row Vector × Column Vector** – Multiplies a row vector with a column vector to create a multiplication table.
2. **Scalar Broadcasting** – Adds a single value (scalar) to every element of an array.
3. **1D Array + 2D Array** – Adds a one-dimensional array to each row of a two-dimensional array.
4. **Column Vector Broadcasting** – Adds a column vector to each column of a two-dimensional array.
5. **Broadcasting Error** – Demonstrates an error when two arrays have incompatible shapes and cannot be broadcast together.

This example helps understand how NumPy automatically expands arrays to perform operations efficiently while also showing situations where broadcasting is not possible.

In [24]:
# Cell 7

# 1. Row Vector × Column Vector 
array1 = np.array([[1,2,3,4,5]])
array2 = np.array([[1],[2],[3],[4],[5]])

print("1. Row Vector * Column Vector")

print("Array 1 Shape:",array1.shape)
print("Array 2 Shape:",array2.shape)

print(array1 * array2)

# 2. Scalar Broadcasting
print("\n2. Scalar Broadcasting")

array = np.array([1,2,3,4,5,])

print(array + 5)

# 3. 1D Array + 2D Array
print("\n3. 1D Array + 2D Array")

array1 = np.array([[1,2,3],
                                        [4,5,6]])

array2 = np.array([10,20,30])

print(array1 + array2)

# 4. Column Vector Broadcasting
print("\n4. Column Vector Broadcasting")

array1 = np.array([[1,2,3],
                                        [4,5,6]])

array2 = np.array([[10],[20]])

print(array1 + array2)

# 5. Broadcasting Error
print("\n5. Broadcasting Error")

array1 = np.array([[1,2,3]])
array2 = np.array([[1,2]])

try: 
    print(array1 + array2)
except ValueError as e:
    print("Error:", e)

1. Row Vector * Column Vector
Array 1 Shape: (1, 5)
Array 2 Shape: (5, 1)
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]

2. Scalar Broadcasting
[ 6  7  8  9 10]

3. 1D Array + 2D Array
[[11 22 33]
 [14 25 36]]

4. Column Vector Broadcasting
[[11 12 13]
 [24 25 26]]

5. Broadcasting Error
Error: operands could not be broadcast together with shapes (1,3) (1,2) 
