# Cell 1: Import NumPy

NumPy is a Python library used for working with arrays and numerical calculations.

In this cell, we import NumPy and give it the short name `np`, which is the standard way of using NumPy.


In [96]:
# Cell 1

# Import the NumPy library
import numpy as np

# Cell 2: Check NumPy Version

Every library has different versions.

This cell prints the installed version of NumPy so we know which version we are using.

In [97]:
# Cell 2

# Print the installed NumPy version
print(np.__version__)

2.3.5


# Cell 3: Creating a 1D Array

A 1D array is similar to a Python list but is much faster for mathematical operations.

In this cell, we:
- Create a NumPy array.
- Multiply every element by 2.
- Print the updated array.
- Print the data type of the object.

In [98]:
# Cell 3

# Create a 1D NumPy array
array = np.array([1,2,3,4])

# Multiply every element by 2
array = array * 2

# Print the updated array
print (array)

# Print the type of the object
print (type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


# Cell 4: Creating a 3D Array

A 3D array contains multiple 2D arrays.

In this example:
- We create a 3 × 3 × 3 array containing letters.
- Print the number of dimensions.
- Print the shape of the array.
- Access one specific element using indexing.
- Combine three letters to form a word.

In [99]:
# Cell 4

# Create a 3D NumPy array

array = np.array([[["A","B","C"], ["D","E","F"], ["G","H","I"]],
                                        [["J","K","L"], ["M","N","O"], ["P","Q","R"]],
                                        [["S","T","U"], ["V","W","X"], ["Y","Z","_"]]])

# Print the number of dimensions
print(array.ndim)

# Print the shape (layers, rows, columns)
print(array.shape)

# Access a specific element
print(array[1,1,1])

# Combine letters from different positions to create a word
word = array[0,0,0] + array[2,0,0] + array[1,0,1]

# Print the final word
print(word)

3
(3, 3, 3)
N
ASK


# Cell 5: NumPy Slicing in a 2D Array

In this cell, we create a **4 × 4 NumPy array** and perform different types of slicing and indexing operations.

The following operations are demonstrated:

1. **Access a Single Element** – Retrieve one specific value using row and column indexes.
2. **Access a Complete Row** – Retrieve all elements from a selected row.
3. **Access a Complete Column** – Retrieve all elements from a selected column.
4. **Slice Rows** – Select multiple rows from the array.
5. **Slice Columns** – Select multiple columns from the array.
6. **Submatrix** – Select a smaller section of the array by slicing both rows and columns.
7. **Every Second Row** – Retrieve every alternate row using the step value.
8. **Every Second Column** – Retrieve every alternate column using the step value.
9. **Reverse Rows** – Display the rows in reverse order.
10. **Reverse Columns** – Display the columns in reverse order.
11. **Reverse Entire Matrix** – Reverse both rows and columns to flip the entire matrix.
12. **Main Diagonal** – Extract the diagonal elements from the array.

This example helps understand the basic slicing and indexing techniques used with 2D NumPy arrays.

In [100]:
# Cell 5

# Create a 4 × 4 NumPy array
array = np.array([[1,2,3,4],
                                        [5,6,7,8],
                                        [9,10,11,12],
                                        [13,14,15,16]])

print("Original Array")
print(array)

# 1. Access a Single Element
print("\n1. Single Element:")
print(array[2,1])

# 2. Access a Complete Row
print("\n2. Complete Row")
print(array[1])

# 3. Access a Complete Column
print("\n3. Complete Column:")
print(array[:,2])

# 4. Slice Rows
print("\n4. Slice Rows:")
print(array[1:3])

# 5. Slice Columns
print("\n5. Slice Columns:")
print(array[:, 1:3])

# 6. Slice Rows and Columns (Submatrix)
print("\n6. Submatrix:")
print(array[1:3, 1:3])

# 7. Every Second Row
print("\n7. Every Second row:")
print(array[::2])

# 8. Every Second Column
print("\n8. Every Second Column")
print(array[:, ::2])

# 9. Reverse Rows
print("\n9. Reverse Rows:")
print(array[::-1])

# 10. Reverse Columns
print("\n10. Reverse Columns:")
print(array[:, ::-1])

# 11. Reverse Entire Matrix
print("\n11. Reverse Entire Matrix:")
print(array[::-1, ::-1])

# 12. Main Diagonal
print("\n12. Main Diagonal:")
print(array.diagonal())

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

1. Single Element:
10

2. Complete Row
[5 6 7 8]

3. Complete Column:
[ 3  7 11 15]

4. Slice Rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]

5. Slice Columns:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

6. Submatrix:
[[ 6  7]
 [10 11]]

7. Every Second row:
[[ 1  2  3  4]
 [ 9 10 11 12]]

8. Every Second Column
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

9. Reverse Rows:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

10. Reverse Columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

11. Reverse Entire Matrix:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

12. Main Diagonal:
[ 1  6 11 16]


# Cell 6: NumPy Arithmetic and Mathematical Operations

In this cell, we create a **1D NumPy array** containing decimal values and perform different arithmetic and mathematical operations.

The following operations are demonstrated:

1. **Addition** – Adds a value to each element of the array.
2. **Subtraction** – Subtracts a value from each element.
3. **Multiplication** – Multiplies each element by a value.
4. **Division** – Divides each element by a value.
5. **Power** – Raises each element to a specified power.
6. **Modulus** – Returns the remainder after division.
7. **Square Root** – Calculates the square root of each element.
8. **Absolute Value** – Returns the positive value of each element.
9. **Round** – Rounds each element to the nearest integer.
10. **Floor** – Rounds each element down to the nearest integer.
11. **Ceiling** – Rounds each element up to the nearest integer.
12. **Exponential** – Calculates the value of \(e^x\) for each element.
13. **Natural Logarithm** – Computes the natural logarithm (base \(e\)) of each element.
14. **Log Base 10** – Computes the logarithm with base 10.
15. **Sine** – Calculates the sine of each element.
16. **Cosine** – Calculates the cosine of each element.
17. **Tangent** – Calculates the tangent of each element.
18. **Maximum Value** – Finds the largest value in the array.
19. **Minimum Value** – Finds the smallest value in the array.
20. **Clip Values** – Limits all values within a specified range.
21. **Pi Constant** – Displays the mathematical constant π (pi).

This example demonstrates the most commonly used arithmetic and mathematical functions available in NumPy.

In [101]:
# Cell 6

# Create a NumPy array
array = np.array([1.99,2.99,3.99])

print("Original Array:")
print(array)

# 1. Addition
print("\n1. Addition (+1):")
print(array  + 1)

# 2. Subtraction
print("\n2. Subtraction (-2):")
print(array - 2)

# 3. Multiplication
print("\n3. Multiplication (*3):")
print(array * 3)

# 4. Division
print("\n4. Division (/4):")
print(array / 4)

# 5. Power
print("\n5. Power(**5):")
print(array ** 5)

# 6. Modulus
print("\n6. Modulus (%2):")
print(array % 2)

# 7. Square Root
print("\n7. Square Root:")
print(np.sqrt(array))

# 8. Absolute Value
print("\n8. Absolute Value:")
print(np.abs(array))

# 9. Round
print("\n9. Round:")
print(np.round(array))

# 10. Floor
print("\n10. Floor:")
print(np.floor(array))

# 11. Ceiling
print("\n11. Ceiling:")
print(np.ceil(array))

# 12. Exponential (e^x)
print("\n12. Exponential:")
print(np.exp(array))

# 13. Natural Logarithm
print("\n13. Natural Logarithm:")
print(np.log(array))

# 14. Log Base 10
print("\n14. Log Base 10:")
print(np.log10(array))

# 15. Sine
print("\n15. Sine:")
print(np.sin(array))

# 16. Cosine
print("\n16. Cosine:")
print(np.cos(array))

# 17. Tangent
print("\n17. Tangent:")
print(np.tan(array))

# 18. Maximum Value
print("\n18. Maximum Values:")
print(np.max(array))

# 19. Minimum Value
print("\n19. Minimum Value:")
print(np.min(array))

# 20. Clip Values (2 to 3)
print("\n20. Clip Values (2 to 3):")
print(np.clip(array,2,3))

# 21. Pi Constant
print("\n21. Pi Constant:")
print(np.pi)

Original Array:
[1.99 2.99 3.99]

1. Addition (+1):
[2.99 3.99 4.99]

2. Subtraction (-2):
[-0.01  0.99  1.99]

3. Multiplication (*3):
[ 5.97  8.97 11.97]

4. Division (/4):
[0.4975 0.7475 0.9975]

5. Power(**5):
[  31.2079601   238.97691015 1011.2638402 ]

6. Modulus (%2):
[1.99 0.99 1.99]

7. Square Root:
[1.4106736  1.72916165 1.99749844]

8. Absolute Value:
[1.99 2.99 3.99]

9. Round:
[2. 3. 4.]

10. Floor:
[1. 2. 3.]

11. Ceiling:
[2. 3. 4.]

12. Exponential:
[ 7.31553376 19.88568249 54.05488936]

13. Natural Logarithm:
[0.68813464 1.09527339 1.38379123]

14. Log Base 10:
[0.29885308 0.47567119 0.6009729 ]

15. Sine:
[ 0.91341336  0.15101271 -0.75022833]

16. Cosine:
[-0.40703321 -0.98853182 -0.66117884]

17. Tangent:
[-2.24407578 -0.15276464  1.13468291]

18. Maximum Values:
3.99

19. Minimum Value:
1.99

20. Clip Values (2 to 3):
[2.   2.99 3.  ]

21. Pi Constant:
3.141592653589793


# Cell 7: NumPy Broadcasting

In this cell, we demonstrate the concept of **broadcasting** in NumPy.

Broadcasting is a feature that allows NumPy to perform arithmetic operations on arrays of different shapes without manually resizing them. NumPy automatically expands the smaller array to match the shape of the larger array whenever the dimensions are compatible.

The following broadcasting examples are demonstrated:

1. **Row Vector × Column Vector** – Multiplies a row vector with a column vector to create a multiplication table.
2. **Scalar Broadcasting** – Adds a single value (scalar) to every element of an array.
3. **1D Array + 2D Array** – Adds a one-dimensional array to each row of a two-dimensional array.
4. **Column Vector Broadcasting** – Adds a column vector to each column of a two-dimensional array.
5. **Broadcasting Error** – Demonstrates an error when two arrays have incompatible shapes and cannot be broadcast together.

This example helps understand how NumPy automatically expands arrays to perform operations efficiently while also showing situations where broadcasting is not possible.

In [102]:
# Cell 7

# 1. Row Vector × Column Vector 
array1 = np.array([[1,2,3,4,5]])
array2 = np.array([[1],[2],[3],[4],[5]])

print("1. Row Vector * Column Vector")

print("Array 1 Shape:",array1.shape)
print("Array 2 Shape:",array2.shape)

print(array1 * array2)

# 2. Scalar Broadcasting
print("\n2. Scalar Broadcasting")

array = np.array([1,2,3,4,5,])

print(array + 5)

# 3. 1D Array + 2D Array
print("\n3. 1D Array + 2D Array")

array1 = np.array([[1,2,3],
                                        [4,5,6]])

array2 = np.array([10,20,30])

print(array1 + array2)

# 4. Column Vector Broadcasting
print("\n4. Column Vector Broadcasting")

array1 = np.array([[1,2,3],
                                        [4,5,6]])

array2 = np.array([[10],[20]])

print(array1 + array2)

# 5. Broadcasting Error
print("\n5. Broadcasting Error")

array1 = np.array([[1,2,3]])
array2 = np.array([[1,2]])

try: 
    print(array1 + array2)
except ValueError as e:
    print("Error:", e)

1. Row Vector * Column Vector
Array 1 Shape: (1, 5)
Array 2 Shape: (5, 1)
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]

2. Scalar Broadcasting
[ 6  7  8  9 10]

3. 1D Array + 2D Array
[[11 22 33]
 [14 25 36]]

4. Column Vector Broadcasting
[[11 12 13]
 [24 25 26]]

5. Broadcasting Error
Error: operands could not be broadcast together with shapes (1,3) (1,2) 


# Cell 8: NumPy Aggregate Functions

In this cell, we create a **2 × 5 NumPy array** and apply different aggregate functions to analyze the data.

Aggregate functions are used to calculate summary statistics such as the total, average, minimum, maximum, and other useful values from an array.

The following aggregate functions are demonstrated:

1. **Sum** – Calculates the total of all elements.
2. **Mean** – Calculates the average of all elements.
3. **Median** – Returns the middle value of the sorted data.
4. **Standard Deviation** – Measures how much the values are spread from the mean.
5. **Variance** – Measures the variation of the data.
6. **Minimum Value** – Finds the smallest element in the array.
7. **Maximum Value** – Finds the largest element in the array.
8. **Index of Minimum Value** – Returns the position of the smallest element.
9. **Index of Maximum Value** – Returns the position of the largest element.
10. **Product** – Multiplies all elements of the array.
11. **Cumulative Sum** – Returns the running total of the elements.
12. **Cumulative Product** – Returns the running product of the elements.
13. **Sum (axis=0)** – Calculates the sum of each column.
14. **Sum (axis=1)** – Calculates the sum of each row.
15. **Mean (axis=0)** – Calculates the average of each column.
16. **Mean (axis=1)** – Calculates the average of each row.
17. **Minimum (axis=0)** – Finds the minimum value in each column.
18. **Minimum (axis=1)** – Finds the minimum value in each row.
19. **Maximum (axis=0)** – Finds the maximum value in each column.
20. **Maximum (axis=1)** – Finds the maximum value in each row.
21. **Standard Deviation (axis=0)** – Calculates the standard deviation of each column.
22. **Standard Deviation (axis=1)** – Calculates the standard deviation of each row.
23. **Variance (axis=0)** – Calculates the variance of each column.
24. **Variance (axis=1)** – Calculates the variance of each row.

This example demonstrates the most commonly used aggregate functions in NumPy and shows how the `axis` parameter can be used to perform calculations across rows or columns.

In [103]:
# Cell 8


# Create a 2 × 5 NumPy array
array = np.array([[1,2,3,4,5],
                                        [6,7,8,9,10]])

print("Original Array:")
print(array)

# 1. Sum
print("\n1. Sum:")
print(np.sum(array))

# 2. Mean
print("\n2. Mean:")
print(np.mean(array))

# 3. Median
print("\n3. Median:")
print(np.median(array))

# 4. Standard Deviation
print("\n4. Standard Deviation:")
print(np.std(array))

# 5. Variance
print("\n5. Variance:")
print(np.var(array))

# 6. Minimum Value
print("\n6. Minimum Value")
print(np.min(array))

# 7. Maximum Value
print("\n7. Maximum Value:")
print(np.max(array))

# 8. Index of Minimum Value
print("\n8. Index of Minimum Value:")
print(np.argmin(array))

# 9. Index of Maximum Value
print("\n9. Index of Maximum Value:")
print(np.argmax(array))

# 10. Product of All Elements
print("\n10. Product:")
print(np.prod(array))  

# 11. Cumulative Sum
print("\n11. Cumulative Sum:")
print(np.cumsum(array))

# 12. Cumulative Product
print("\n12. Cumulative Product:")
print(np.cumprod(array))

# 13. Sum Along Columns
print("\n13. Sum (axis=0):")
print(np.sum(array, axis=0))

# 14. Sum Along Rows
print("\n14. Sum (axis=1):")
print(np.sum(array, axis=1))

# 15. Mean Along Columns
print("\n15. Mean (axis=0):")
print(np.mean(array, axis=0))

# 16. Mean Along Rows
print("\n16. Mean (axis=1):")
print(np.mean(array, axis=1))

# 17. Minimum Along Columns
print("\n17. Minimum(axis=0):")
print(np.min(array, axis=0))

# 18. Minimum Along Rows
print("\n18. Minimum (axis=1):")
print(np.min(array, axis=1))

# 19. Maximum Along Columns
print("\n19. Maximum (axis=0):")
print(np.max(array, axis=0))

# 20. Maximum Along Rows
print("\n20. Maximum (axis=1):")
print(np.max(array, axis=1))

# 21. Standard Deviation Along Columns
print("\n21. Standard Deviation (axis=0):")
print(np.std(array, axis=0))

# 22. Standard Deviation Along Rows
print("\n22. Standard Deviation (axis=1):")
print(np.std(array,axis=1))

# 23. Variance Along Columns
print("\n23. Variance (axis=0):")
print(np.var(array, axis=0))

# 24. Variance Along Rows
print("\n24. Variance (axis=1):")
print(np.var(array, axis=1))

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

1. Sum:
55

2. Mean:
5.5

3. Median:
5.5

4. Standard Deviation:
2.8722813232690143

5. Variance:
8.25

6. Minimum Value
1

7. Maximum Value:
10

8. Index of Minimum Value:
0

9. Index of Maximum Value:
9

10. Product:
3628800

11. Cumulative Sum:
[ 1  3  6 10 15 21 28 36 45 55]

12. Cumulative Product:
[      1       2       6      24     120     720    5040   40320  362880
 3628800]

13. Sum (axis=0):
[ 7  9 11 13 15]

14. Sum (axis=1):
[15 40]

15. Mean (axis=0):
[3.5 4.5 5.5 6.5 7.5]

16. Mean (axis=1):
[3. 8.]

17. Minimum(axis=0):
[1 2 3 4 5]

18. Minimum (axis=1):
[1 6]

19. Maximum (axis=0):
[ 6  7  8  9 10]

20. Maximum (axis=1):
[ 5 10]

21. Standard Deviation (axis=0):
[2.5 2.5 2.5 2.5 2.5]

22. Standard Deviation (axis=1):
[1.41421356 1.41421356]

23. Variance (axis=0):
[6.25 6.25 6.25 6.25 6.25]

24. Variance (axis=1):
[2. 2.]


# Cell 9: NumPy Filtering

In this cell, we demonstrate **filtering** in NumPy.

Filtering is the process of selecting elements from an array that satisfy a specific condition. It is commonly used for searching, cleaning, and analyzing data.

The following filtering operations are demonstrated:

1. **Teenagers** – Selects all ages less than 18.
2. **Adults** – Selects ages between 18 and 64 using multiple conditions.
3. **Seniors** – Selects ages greater than or equal to 65.
4. **Even Ages** – Selects all even numbers.
5. **Odd Ages** – Selects all odd numbers.
6. **np.where() with 0** – Preserves the array shape by replacing values that do not satisfy the condition with 0.
7. **np.where() with -1** – Preserves the array shape by replacing values that do not satisfy the condition with -1.
8. **Greater Than (>)** – Selects values greater than a specified number.
9. **Less Than or Equal To (<=)** – Selects values less than or equal to a specified number.
10. **Equal To (==)** – Selects values equal to a specified number.
11. **Not Equal To (!=)** – Selects values that are not equal to a specified number.
12. **AND (&)** – Selects values that satisfy two conditions at the same time.
13. **OR (|)** – Selects values that satisfy either of two conditions.
14. **Conditional Replacement** – Replaces values based on a condition using `np.where()`.
15. **Value Limiting** – Replaces values above a specified limit using `np.where()`.

This example demonstrates Boolean Indexing, Comparison Operators, Logical Operators (`&` and `|`), the Modulus Operator (`%`), and the `np.where()` function for filtering and modifying NumPy arrays.

In [104]:
# cell 9

# Create a 2 × 8 NumPy array
ages = np.array([[21,17,19,20,16,30,18,65],
                                    [39,22,15,99,18,19,20,21]])

print("Original Array:")
print(ages)

# 1. Teenagers (Age < 18)
print("\n1. Teenagers (Age<18):")
teenagers = ages[ages<18]
print(teenagers)

# 2. Adults (18 <= Age < 65)
print("\n2. Adults (18 <= Age < 65):")
adults = ages[(ages >= 18) & (ages <65)]
print(adults)

# 3. Seniors (Age >= 65)
print("\n3. Seniors (Age >= 65):")
seniors = ages[ages >= 65]
print(seniors)

# 4. Even Ages
print("\n4. Even Ages:")
evens = ages[ages % 2 == 0]
print(evens)

# 5. Odd Ages
print("\n5. Odd Ages:")
odds = ages[ages % 2 != 0]
print(odds)

# 6. Adults using np.where()
print("\n6. Adults using np.where():")
adults = np.where(ages >= 18, ages, 0)
print(adults)

# 7. Adults using np.where() (-1 Fill Value)
print("\n7. Adults using np.where() (-1 Fill Value):")
adults = np.where(ages >= 18, ages, -1)
print(adults)

# 8. Ages Greater Than 20
print("\n8. Ages Greater Than 20:")
print(ages[ages> 20])

# 9. Ages Less Than or Equal to 20
print("\n9. Ages Less Than or Equal to 20:")
print(ages[ages <= 20])

# 10. Ages Equal to 18
print("\n10. Ages Equal to 18:")
print(ages[ages == 18])

# 11. Ages Not Equal to 18
print("\n11. Ages Not Equal to 18:")
print(ages[ages != 18])

# 12. Age Between 20 and 40
print("\n12. Age Between 20 and 40:")
print(ages[(ages >= 20) & (ages <= 40)])

# 13. Age Less Than 18 OR Greater Than 65
print("\n13. Age Less Than 18 OR Greater Than 65:")
print(ages[(ages < 18) | (ages > 65)])

# 14. Replace Ages Less Than 18 with 0
print("\n14. Replace Ages Less Than 18 with 0:")
print(np.where(ages < 18, 0, ages))

# 15. Replace Ages Greater Than 65 with 65
print("\n15. Replace Ages Greater Than 65 with 65:")
print(np.where(ages > 65, 65, ages))

Original Array:
[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]

1. Teenagers (Age<18):
[17 16 15]

2. Adults (18 <= Age < 65):
[21 19 20 30 18 39 22 18 19 20 21]

3. Seniors (Age >= 65):
[65 99]

4. Even Ages:
[20 16 30 18 22 18 20]

5. Odd Ages:
[21 17 19 65 39 15 99 19 21]

6. Adults using np.where():
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]

7. Adults using np.where() (-1 Fill Value):
[[21 -1 19 20 -1 30 18 65]
 [39 22 -1 99 18 19 20 21]]

8. Ages Greater Than 20:
[21 30 65 39 22 99 21]

9. Ages Less Than or Equal to 20:
[17 19 20 16 18 15 18 19 20]

10. Ages Equal to 18:
[18 18]

11. Ages Not Equal to 18:
[21 17 19 20 16 30 65 39 22 15 99 19 20 21]

12. Age Between 20 and 40:
[21 20 30 39 22 20 21]

13. Age Less Than 18 OR Greater Than 65:
[17 16 15 99]

14. Replace Ages Less Than 18 with 0:
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]

15. Replace Ages Greater Than 65 with 65:
[[21 17 19 20 16 30 18 65]
 [39 22 15 65 18 19 20 21]]


# Cell 10: NumPy Random Numbers

In this cell, we demonstrate how to generate **random numbers** using NumPy.

Random numbers are useful for simulations, testing, machine learning, games, and data generation.

The following examples are demonstrated:

1. **Random Integer** – Generates a random integer within a specified range.
2. **Random Integer (1–100)** – Generates a random number between 1 and 100.
3. **Multiple Random Integers** – Generates multiple random integers in a 1D array.
4. **2D Random Integer Array** – Generates a matrix of random integers.
5. **Seed** – Produces the same random values every time the program runs.
6. **Random Float (0–1)** – Generates a random decimal number.
7. **Random Float (-1 to 1)** – Generates decimal values within a custom range.
8. **Multiple Random Floats** – Creates a 1D array of floating-point values.
9. **2D Random Float Array** – Creates a matrix of floating-point values.
10. **Shuffle** – Randomly rearranges the elements of an array.
11. **Random Choice** – Selects one random element from an array.
12. **Multiple Random Choices** – Selects several random elements.
13. **2D Random Choice** – Creates a matrix of randomly selected elements.
14. **Random Boolean Values** – Generates random `True` and `False` values.
15. **Random Selection from a Custom List** – Randomly selects values from a user-defined array.

This cell demonstrates the `default_rng()` random number generator, the `integers()`, `uniform()`, `shuffle()`, and `choice()` methods, along with the use of seeds for reproducible results.

In [105]:
# cell 10

# Create Random Number Generator (RNG)

rng = np.random.default_rng()

# 1. Random Integer (Dice)
print("1. Random Integer (1-6):")
print(rng.integers(low=1, high=7))

# 2. Random Integer (1-100)
print("\n2. Random Integer (1-100):")
print(rng.integers(low=1, high=101))

# 3. Three Random Integers
print("\n3. Three Random Integers:")
print(rng.integers(low=1, high=101, size=3))

# 4. 3×2 Random Integer Array
print("\n4. 3*2 Random Integer Array:")
print(rng.integers(low=1, high=101, size=(3,2)))

# 5. Seed Example
print("\n5. Random Number using Seed:")
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=101, size=5))

# 6. Random Float (0 to 1)
print("\n6. Random Float (0 to 1):")
print(rng.uniform())

# 7. Random Float (-1 to 1)
print("\n7. Random Float (-1 to 1):")
print(rng.uniform(low=-1, high=1))

# 8. Three Random Floats
print("\n8. Three Randomm Floats:")
print(rng.uniform(low=-1, high=1, size=3))

# 9. 3×2 Random Float Array
print("\n9. 3*2 Random Float array:")
print(rng.uniform(low=-1, high=1, size=(3,2)))

# 10. Shuffle an Array
array = np.array([1,2,3,4,5])

print("\n10. Original Array:")
print(array)

rng.shuffle(array)
print("Shuffled Array:")
print(array)

# 11. Random Choice (Single Fruit)
fruits = np.array(["Apple","Orange","Coconut","Banana","Pineapple"])
print("\n11. Random Fruits:")
print(rng.choice(fruits))

# 12. Three Random Fruits
print("\n12. Three Random Fruits:")
print(rng.choice(fruits, size=3))

# 13. 3×3 Random Fruits
print("\n13. 3*3 Random Fruits:")
print(rng.choice(fruits, size=(3,3)))

# 14. Random Boolean Values
print("\n14. Random Boolean Values:")
print(rng.choice([True, False], size=10))

# 15. Random Numbers from Custom List
numbers = np.array([10,20,30,40,50])
print("\n15. Random Numbers from Custom List:")
print(rng.choice(numbers, size=5))

1. Random Integer (1-6):
6

2. Random Integer (1-100):
44

3. Three Random Integers:
[39 92  2]

4. 3*2 Random Integer Array:
[[93 77]
 [41 74]
 [60 49]]

5. Random Number using Seed:
[48 52 76 96  4]

6. Random Float (0 to 1):
0.9486494471372439

7. Random Float (-1 to 1):
-0.3763370959790291

8. Three Randomm Floats:
[-0.1533471   0.65540519 -0.18160173]

9. 3*2 Random Float array:
[[ 0.09918738 -0.94488177]
 [ 0.50702622  0.07628663]
 [-0.34053657  0.57685741]]

10. Original Array:
[1 2 3 4 5]
Shuffled Array:
[4 2 1 3 5]

11. Random Fruits:
Apple

12. Three Random Fruits:
['Orange' 'Coconut' 'Pineapple']

13. 3*3 Random Fruits:
[['Orange' 'Coconut' 'Orange']
 ['Apple' 'Banana' 'Apple']
 ['Orange' 'Coconut' 'Coconut']]

14. Random Boolean Values:
[ True False False False  True False  True False False  True]

15. Random Numbers from Custom List:
[40 10 20 50 30]
