# Import NumPy

NumPy is a Python library used for working with arrays and numerical calculations.

In this cell, we import NumPy and give it the short name `np`, which is the standard way of using NumPy.


In [19]:
# Cell 1

# Import the NumPy library
import numpy as np

# Check NumPy Version

Every library has different versions.

This cell prints the installed version of NumPy so we know which version we are using.

In [20]:
# Cell 2

# Print the installed NumPy version
print(np.__version__)

2.3.5


# Creating a 1D Array

A 1D array is similar to a Python list but is much faster for mathematical operations.

In this cell, we:
- Create a NumPy array.
- Multiply every element by 2.
- Print the updated array.
- Print the data type of the object.

In [21]:
# Cell 3

# Create a 1D NumPy array
array = np.array([1,2,3,4])

# Multiply every element by 2
array = array * 2

# Print the updated array
print (array)

# Print the type of the object
print (type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


# Creating a 3D Array

A 3D array contains multiple 2D arrays.

In this example:
- We create a 3 × 3 × 3 array containing letters.
- Print the number of dimensions.
- Print the shape of the array.
- Access one specific element using indexing.
- Combine three letters to form a word.

In [22]:
# Cell 4

# Create a 3D NumPy array

array = np.array([[["A","B","C"], ["D","E","F"], ["G","H","I"]],
                                        [["J","K","L"], ["M","N","O"], ["P","Q","R"]],
                                        [["S","T","U"], ["V","W","X"], ["Y","Z","_"]]])

# Print the number of dimensions
print(array.ndim)

# Print the shape (layers, rows, columns)
print(array.shape)

# Access a specific element
print(array[1,1,1])

# Combine letters from different positions to create a word
word = array[0,0,0] + array[2,0,0] + array[1,0,1]

# Print the final word
print(word)

3
(3, 3, 3)
N
ASK


# NumPy Slicing in a 2D Array

In this cell, we create a **4 × 4 NumPy array** and perform different types of slicing and indexing operations.

The following operations are demonstrated:

1. **Access a Single Element** – Retrieve one specific value using row and column indexes.
2. **Access a Complete Row** – Retrieve all elements from a selected row.
3. **Access a Complete Column** – Retrieve all elements from a selected column.
4. **Slice Rows** – Select multiple rows from the array.
5. **Slice Columns** – Select multiple columns from the array.
6. **Submatrix** – Select a smaller section of the array by slicing both rows and columns.
7. **Every Second Row** – Retrieve every alternate row using the step value.
8. **Every Second Column** – Retrieve every alternate column using the step value.
9. **Reverse Rows** – Display the rows in reverse order.
10. **Reverse Columns** – Display the columns in reverse order.
11. **Reverse Entire Matrix** – Reverse both rows and columns to flip the entire matrix.
12. **Main Diagonal** – Extract the diagonal elements from the array.

This example helps understand the basic slicing and indexing techniques used with 2D NumPy arrays.

In [44]:
# Cell 5

# Create a 4 × 4 NumPy array
array = np.array([[1,2,3,4],
                                        [5,6,7,8],
                                        [9,10,11,12],
                                        [13,14,15,16]])

print("Original Array")
print(array)

# 1. Access a Single Element
print("\n1. Single Element:")
print(array[2,1])

# 2. Access a Complete Row
print("\n2. Complete Row")
print(array[1])

# 3. Access a Complete Column
print("\n3. Complete Column:")
print(array[:,2])

# 4. Slice Rows
print("\n4. Slice Rows:")
print(array[1:3])

# 5. Slice Columns
print("\n5. Slice Columns:")
print(array[:, 1:3])

# 6. Slice Rows and Columns (Submatrix)
print("\n6. Submatrix:")
print(array[1:3, 1:3])

# 7. Every Second Row
print("\n7. Every Second row:")
print(array[::2])

# 8. Every Second Column
print("\n8. Every Second Column")
print(array[:, ::2])

# 9. Reverse Rows
print("\n9. Reverse Rows:")
print(array[::-1])

# 10. Reverse Columns
print("\n10. Reverse Columns:")
print(array[:, ::-1])

# 11. Reverse Entire Matrix
print("\n11. Reverse Entire Matrix:")
print(array[::-1, ::-1])

# 12. Main Diagonal
print("\n12. Main Diagonal:")
print(array.diagonal())

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

1. Single Element:
10

2. Complete Row
[5 6 7 8]

3. Complete Column:
[ 3  7 11 15]

4. Slice Rows:
[[ 5  6  7  8]
 [ 9 10 11 12]]

5. Slice Columns:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

6. Submatrix:
[[ 6  7]
 [10 11]]

7. Every Second row:
[[ 1  2  3  4]
 [ 9 10 11 12]]

8. Every Second Column
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]

9. Reverse Rows:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

10. Reverse Columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

11. Reverse Entire Matrix:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

12. Main Diagonal:
[ 1  6 11 16]
